baseURL = "https://www.dgdavid.es"
languageCode = "en"
title = "David Díaz's blog"
publishDir = "docs"
theme = "kiss"
enableEmoji = true
disqusShortname = "dgdavid"

[params.info]
poweredby = true # Adds powered by Hugo and Kiss below Copyright section

[params.assets]
customCSS = ["css/custom.css"]

[params.social]
github = "dgdavid"
linkedin = "diazglezdavid"

[params.sections_right]
"/blog/hi-there/" = "About me"

[blackfriday]
hrefTargetBlank = true
